export const SET_SUDOKU = "SET_SUDOKU";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_LOADING = "SET_LOADING";
export const SET_INITIAL_SUDOKU = "SET_INITIAL_SUDOKU";
export const SET_PLAYER_NAME = "SET_PLAYER_NAME";
